import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/button'
import CountdownBar from '../components/countdown-bar'
import Details from '../components/details'
import Footer from '../components/footer'
import Hero from '../components/hero'
import Schedule from '../components/schedule'
import { registrationLink } from '../EDITME'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/jfz7vwd.css" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <CountdownBar />
        <Schedule />
        <Details />
      </main>

      <Footer />
    </div>
  )
}

export default Home
